BEGIN;

ALTER TABLE spells
  ADD COLUMN IF NOT EXISTS page_rev_id BIGINT,
  ADD COLUMN IF NOT EXISTS last_rev_ts TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS categories TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS realities TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS first_appearance TEXT,
  ADD COLUMN IF NOT EXISTS aliases TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS infobox JSONB,
  ADD COLUMN IF NOT EXISTS sections JSONB,
  ADD COLUMN IF NOT EXISTS outlinks JSONB,
  ADD COLUMN IF NOT EXISTS embedding vector(768);

COMMIT;
